# eks or local: boolean
eks: false

nginx:
  syncWave: "1"
  spec:
    source:
      targetRevision: '4.8.3'
      helm:
        valuesObject:
            controller:
              extraArgs:
                http: 80
                https: 443
              containerPort:
                http: 80
                https: 443
              image:
                allowPrivilegeEscalation: true
              service:
                type: LoadBalancer

eso:
  syncWave: "2"
  spec:
    source:
      targetRevision: '0.9.7'

manifests:
  syncWave: "3"
  spec:
    source:
      helm:
        valuesObject:
            eks: false

