# eks or local: boolean
eks: true

awsLBC:
  syncWave: "2"
  spec:
    source:
      targetRevision: 'v1.6.2'
      chart: aws-load-balancer-controller
      repoURL: https://aws.github.io/eks-charts
      helm:
        releaseName: aws-load-balancer-controller
        valuesObject:
            clusterName: kodiko 
            serviceAccount:
                create: false
                name: aws-load-balancer-controller
            region: ap-south-1
            # update EKS VPC ID
            vpcId: 
  destination:
    server: https://kubernetes.default.svc
    ns: kube-system


nginx:
  syncWave: "3"
  spec:
    source:
      targetRevision: '4.8.3'
      chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      helm:
        releaseName: ingress-nginx
        valuesObject:
            controller:
              extraArgs:
                http: 8080
                https: 8081
              containerPort:
                http: 8080
                https: 8081
              image:
                allowPrivilegeEscalation: false
              service:
                type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    ns: ingress-nginx

jenkins:
  syncWave: "4"
  spec:
    sources:
      targetRevision: '4.8.3'
      chart: jenkins
      repoURL: https://charts.jenkins.io
      helm:
        releaseName: jenkins
        valuesObject:
          controller:
            jenkinsUrl: "http://localhost:8050"
            componentName: "jenkins-controller"
            image: "annleefores/jenkins-controller"
            tag: "latest"
            imagePullPolicy: "Always"
            numExecutors: 0

            admin:
              existingSecret: jenkins-admin-secret
              userKey: JENKINS_USERNAME
              passwordKey: JENKINS_PASSWORD

            resources:
              requests:
                cpu: "500m"
                memory: "512Mi"
              limits:
                cpu: "2000m"
                memory: "4096Mi"

            JCasC:
              systemMessage: Welcome to Kodiko CI\CD server.  This Jenkins is configured and managed 'as code'.
              
              sonarqube:
                credentials:
                  id: "sonar_token"
                  secret: "secret value"
                  description: "Sonar token"
                installations:
                  name: "sq1"
                  serverUrl: "http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000"
                  credentialsId: sonar_token

              jobs:
                repoURL: https://github.com/annleefores/kodiko.git
                branch: '*/dev'
            
            servicePort: 8050
            targetPort: 8080
            serviceType: LoadBalancer
            installPlugins: false

      extRepoURL: https://github.com/annleefores/kodiko.git
      extBranch: dev
      extPath: kubernetes/system-config/ext-secrets/jenkins

  destination:
    server: https://kubernetes.default.svc
    ns: jenkins

imageUpdater:
  syncWave: "5"
  spec:
    sources:
      targetRevision: '0.9.1'
      chart: argocd-image-updater
      repoURL: https://argoproj.github.io/argo-helm
      helm:
        releaseName: argocd-image-updater
        valuesObject:
            config:
              logLevel: "debug"

      extRepoURL: https://github.com/annleefores/kodiko.git
      extBranch: dev
      extPath: kubernetes/system-config/ext-secrets/argocd-image-updater

  destination:
    server: https://kubernetes.default.svc
    ns: argocd

reloader:
  syncWave: "6"
  spec:
    sources:
      targetRevision: '1.0.51'
      chart: stakater/reloader
      repoURL: https://stakater.github.io/stakater-charts
      helm:
        releaseName: reloader
        valuesObject:
          reloader:
            watchGlobally: false
            isArgoRollouts: true
            reloadOnCreate: true
            syncAfterRestart: true
            ignoreSecrets: true

  destination:
    server: https://kubernetes.default.svc
    ns: kodiko-backend

manifests:
  syncWave: "6"
  spec:
    source:
      branch: dev
      path: kubernetes/system-config/manifests
      repoURL: https://github.com/annleefores/kodiko.git
      helm:
        releaseName: manifests
        valuesObject:
            eks: true
               
  destination:
    server: https://kubernetes.default.svc
    ns: default

sonarqube:
  syncWave: "7"
  spec:
    source:
      targetRevision: '10.3.0'
      chart: sonarqube
      repoURL: https://SonarSource.github.io/helm-chart-sonarqube
      helm:
        releaseName: sonarqube
        valuesObject:
          image:
            tag: 10.3.0-community
            pullPolicy: IfNotPresent

          service:
            type: LoadBalancer
          
          sonarWebContext: "/"

          persistence:
            enabled: true

          readinessProbe:
            failureThreshold: 10

          livenessProbe:
            failureThreshold: 10

          startupProbe:
            failureThreshold: 24

  destination:
    server: https://kubernetes.default.svc
    ns: sonarqube