# eks or local: boolean
eks: false

nginx:
  syncWave: "1"
  spec:
    source:
      targetRevision: '4.8.3'
      chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      helm:
        releaseName: ingress-nginx
        valuesObject:
            controller:
              extraArgs:
                http: 80
                https: 443
              containerPort:
                http: 80
                https: 443
              image:
                allowPrivilegeEscalation: true
              service:
                type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    ns: ingress-nginx


eso:
  syncWave: "2"
  spec:
    source:
      targetRevision: '0.9.7'
      chart: external-secrets
      repoURL: https://charts.external-secrets.io
      helm:
        releaseName: external-secrets
        valuesObject:
            installCRDs: true
            webhook:
              port: 9443
  destination:
    server: https://kubernetes.default.svc
    ns: external-secrets