spec:
  source:
    branch: dev
    path: kubernetes/system-config/config-apps
    repoURL: https://github.com/annleefores/kodiko.git

destination:
  server: https://kubernetes.default.svc
  ns: default