# Change argocd service type to LoadBalancer for dev

spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8081
    protocol: TCP
    targetPort: 8081

  type: LoadBalancer