# docs: 
# https://external-secrets.io/latest/introduction/getting-started/
# https://external-secrets.io/main/provider/aws-parameter-store/


apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key