apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: {{ .Release.Name }}
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: {{ .Values.spec.source.path }}
    helm:
      {{- if .Values.dev }}
      valueFiles:
      - dev-values.yaml
      {{- else }}
      valuesObject:
        awsLBC:
          spec:
            source:
              helm:
                valuesObject:
                    vpcId: {{ .Values.vpcID }} 
      {{- end }}

  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.ns }}
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    