name: kodiko

services:
  backend:
    env_file:
      - ./server/backend/.env
    image: backend
    container_name: backend
    build: ./server/backend
    ports:
      - 8000:8000
    command: "python3 -m uvicorn main:app --port 8000 --host 0.0.0.0 --reload"
    networks:
      - kodiko
    volumes:
      - ./server/backend:/app
      - ~/.kube/config:/home/.kube/config
    restart: on-failure

  frontend:
    env_file:
      - ./web/.env.local
    image: frontend
    container_name: frontend
    build:
      context: web
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    restart: on-failure

  codepod:
    image: codepod-dev
    container_name: codepod-dev
    build:
      context: server/codepod
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server/codepod:/home/.kodiko
    restart: on-failure

networks:
  kodiko:
    driver: bridge
    name: kodiko
