name: kodiko

services:

  backend:
    env_file:
      - ./server/backend/.env
    image: backend
    container_name: backend
    build: ./server/backend
    ports:
      - 8000:8000
    networks:
      - kodiko
    volumes:
      - ./server/backend:/app

  codepod:
    env_file:
      - ./server/codepod/.env
    image: codepod
    container_name: codepod
    build:
      context: server/codepod
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server/codepod:/app

networks:
  kodiko:
    driver: bridge
    name: kodiko
