name: kodiko

services:
  frontend:
    env_file:
      - ./web/.env.local
    image: frontend
    container_name: frontend
    build:
      context: web
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    restart: on-failure
