helm:
  parameters:
  - name: backend.image.name
    value: annleefores/kodiko-backend
    forcestring: true
  - name: backend.image.tag
    value: 1.0.8
    forcestring: true
  - name: cm.codepod.image.name
    value: annleefores/kodiko-codepod
    forcestring: true
  - name: cm.codepod.image.tag
    value: 1-e7d6a41e9cfae7c5838422387b2216b25ca790f9
    forcestring: true
