helm:
  parameters:
  - name: backend.image.name
    value: annleefores/kodiko-backend
    forcestring: true
  - name: backend.image.tag
    value: 10-246653f85c638e8cfd34579c025cabe1bd512ca3
    forcestring: true
  - name: cm.codepod.image.name
    value: annleefores/kodiko-codepod
    forcestring: true
  - name: cm.codepod.image.tag
    value: 2-246653f85c638e8cfd34579c025cabe1bd512ca3
    forcestring: true
