helm:
  parameters:
  - name: backend.image.name
    value: annleefores/kodiko-backend
    forcestring: true
  - name: backend.image.tag
    value: v0.1.4
    forcestring: true
  - name: cm.codepod.image.name
    value: annleefores/kodiko-codepod
    forcestring: true
  - name: cm.codepod.image.tag
    value: v0.1.2
    forcestring: true
