## backend

# dev or prod: bool
dev: true

# make sure this path is added to file sharing in docker desktop
# prefix with /host_mnt for docker desktop
hostPath: /host_mnt/home/annlee/projects/kodiko/server/backend

replicas: 2
backend:
  name: backend
  image:
    name: annleefores/kodiko-backend
    tag: '1.0.0'
memory: "128Mi"
cpu: "500m"
imagePullPolicy: IfNotPresent

type: ClusterIP

ns: kodiko-backend
serviceAccountName: kodiko-backend

# secret values retrieved from AWS parameter store using External Secrets Operator
eso:
  UUID_NAMESPACE: /kodiko/backend/UUID_NAMESPACE
  REGION: /kodiko/backend/REGION
  COGNITO_USER_POOL_ID: /kodiko/backend/COGNITO_USER_POOL_ID
  COGNITO_CLIENT_ID: /kodiko/backend/COGNITO_CLIENT_ID

cm:
  codepod:
    image: annleefores/kodiko-codepod
    tag: 1.0.0




