## backend

# dev or prod: bool
dev: false

# dev env host path to files
hostPath:

replicas: 2
container:
  name: backend
  image:
    name: annleefores/kodiko-backend
    version: latest
memory: "128Mi"
cpu: "500m"
imagePullPolicy: IfNotPresent

type: ClusterIP

ns: kodiko-backend
serviceAccountName: kodiko-backend

# secret values retrieved from AWS parameter store using External Secrets Operator
eso:
  UUID_NAMESPACE: /kodiko/backend/UUID_NAMESPACE
  REGION: /kodiko/backend/REGION
  COGNITO_USER_POOL_ID: /kodiko/backend/COGNITO_USER_POOL_ID
  COGNITO_CLIENT_ID: /kodiko/backend/COGNITO_CLIENT_ID




