apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin-extsecret
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: jenkins-admin-secret
    template:
      engineVersion: v2
      data:
        JENKINS_USERNAME: "{{ `{{ .JENKINS_USERNAME }}` }}"
        JENKINS_PASSWORD: "{{ `{{ .JENKINS_PASSWORD }}` }}"

  data:
  - secretKey: JENKINS_USERNAME
    remoteRef:
      key: /kodiko/backend/local/JENKINS_USERNAME
  - secretKey: JENKINS_PASSWORD
    remoteRef:
      key: /kodiko/backend/local/JENKINS_PASSWORD