apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: external-secrets-operator
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: '0.9.7'
    chart: external-secrets
    helm:
        releaseName: external-secrets
        valuesObject:
            installCRDs: true
            webhook:
              port: 9443

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
    - CreateNamespace=true
    