apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: ingress-nginx-controller
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: '4.8.3'
    chart: ingress-nginx
    helm:
        releaseName: ingress-nginx
        valuesObject:
            controller:
              extraArgs:
                http-port: 8080
                https-port: 8081

              containerPort:
                http: 8080
                https: 8081

              image:
                allowPrivilegeEscalation: false

              service:
                type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
    - CreateNamespace=true
    