{{- with .Values.jenkins }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ quote .syncWave }}
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: jenkins
spec:
  project: default
  source:
    repoURL: {{ .spec.source.repoURL }}
    targetRevision: {{ .spec.source.targetRevision }}
    chart: {{ .spec.source.chart }}
    helm:
        releaseName: jenkins
        {{- with .spec.source.helm.valuesObject }}
        valuesObject:
          controller:
            {{- with .controller }}
            componentName: {{ .componentName }}
            image: {{ .image }}
            tag: {{ .tag }}
            imagePullPolicy: {{ .imagePullPolicy }}
            numExecutors: {{ .numExecutors }}

            resources:
              requests:
                cpu: {{ .resources.requests.cpu }}
                memory: {{ .resources.requests.memory }}
              limits:
                cpu: {{ .resources.limits.cpu }}
                memory: {{ .resources.limits.memory }}
              
            JCasC:
              defaultConfig: true
              configScripts:
                welcome-message: |
                  jenkins:
                    systemMessage: Welcome to Kodiko CI\CD server.  This Jenkins is configured and managed 'as code'.
                pipeline-job: | 
                  jobs:
                    - script: |
                        jobarray = ['backend','codepod']
                        for(currentjob in jobarray)                                     
                        pipelineJob('kodiko-$currentjob') {
                          definition {
                            cpsScm {
                              scm {
                                git {
                                  remote {
                                    url('https://github.com/annleefores/kodiko.git')
                                  }
                                  branch('*/dev')
                                }
                              }
                              scriptPath("server/$currentjob/Jenkinsfile")
                              lightweight()
                            }
                          }
                        } 
                        
            servicePort: {{ .servicePort }}
            targetPort: {{ .targetPort }}
            serviceType: {{ .serviceType }}
            installPlugins: {{ .installPlugins }}
            {{- end }}  
        {{- end }}  

  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.ns }}
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}  