{{- with .Values.kaniko }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ quote .syncWave }}
  name: kaniko
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: kaniko
spec:
  project: default
  source:
    repoURL: {{ .spec.source.repoURL }}
    targetRevision: {{ .spec.source.branch }}
    path: {{ .spec.source.path }}

  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.ns }}
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}  