{{- with .Values.manifests }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ quote .syncWave }}
  name: manifest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: manifest
spec:
  project: default
  source:
    repoURL: {{ .spec.source.repoURL }}
    targetRevision: {{ .spec.source.branch }}
    path: {{ .spec.source.path }}
    helm:
        releaseName: manifests
        {{- with .spec.source.helm.valuesObject }}
        valuesObject:
            eks: {{ .eks }}
        {{- end }}
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.ns }}
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
{{- end }}