apiVersion: batch/v1
kind: Job
metadata:
  name: config-postsync-hook
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: postsync-hook-job
        image: annleefores/config-postsync-hook
        envFrom:
        - secretRef:
            name: postsync-hook-secret
        imagePullPolicy: IfNotPresent
      restartPolicy: Never

  backoffLimit: 2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-postsync-hook
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: postsync-hook-secret
    template:
      engineVersion: v2
      data:
        SONAR_USERNAME: "{{ `{{ .SONAR_USERNAME }}` }}"
        SONAR_PASSWORD: "{{ `{{ .SONAR_PASSWORD }}` }}"
        JENKINS_SONAR_WEBHOOK: "{{ `{{ .JENKINS_SONAR_WEBHOOK }}` }}"
        NAME: "{{ `{{ .NAME }}` }}"
        JENKINS_USERNAME: "{{ `{{ .JENKINS_USERNAME }}` }}"
        JENKINS_PASSWORD: "{{ `{{ .JENKINS_PASSWORD }}` }}"

  data:
  - secretKey: SONAR_USERNAME
    remoteRef:
      key: /kodiko/backend/local/SONAR_USERNAME
  - secretKey: SONAR_PASSWORD
    remoteRef:
      key: /kodiko/backend/local/SONAR_PASSWORD
  - secretKey: JENKINS_SONAR_WEBHOOK
    remoteRef:
      key: /kodiko/backend/local/JENKINS_SONAR_WEBHOOK
  - secretKey: NAME
    remoteRef:
      key: /kodiko/backend/local/NAME
  - secretKey: JENKINS_USERNAME
    remoteRef:
      key: /kodiko/backend/local/JENKINS_USERNAME
  - secretKey: JENKINS_PASSWORD
    remoteRef:
      key: /kodiko/backend/local/JENKINS_PASSWORD