apiVersion: v1
kind: ServiceAccount
metadata:
  name: kodiko-backend
  namespace: {{ .Values.ns }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-rbac-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "delete", "get", "patch"]
- apiGroups: ["", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "delete", "get"]
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets"]
  verbs: ["create", "delete", "get"]


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-rbac-role-binding
subjects:
- kind: ServiceAccount
  name: kodiko-backend
  namespace: {{ .Values.ns }}
roleRef:
  kind: ClusterRole
  name: backend-rbac-role
  apiGroup: rbac.authorization.k8s.io
  