apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image.name }}:{{ .Values.container.image.version }}
          resources:
            limits:
              memory: {{ .Values.memory | quote }}
              cpu: {{ .Values.cpu | quote }}
          ports:
            - containerPort: 8000
          {{- if .Values.dev }}
          volumeMounts:
            - mountPath: /app
              name: dev-volume
          {{- end  }}
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-configmap
          imagePullPolicy: {{ .Values.imagePullPolicy }}
      {{- if .Values.dev }}
      volumes:
        - name: dev-volume
          hostPath:
            # directory location on host
            path: {{ .Values.hostPath }}
            # this field is optional
            type: DirectoryOrCreate
      {{- end  }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: backend
  type: {{ .Values.type }} 
  ports:
    - port: 8000
      targetPort: 8000
