# https://external-secrets.io/main/provider/aws-parameter-store/


apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        {{- if .Values.dev }}
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
            namespace: {{ .Values.ns }}
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: {{ .Values.ns }}

        {{- else }}
        jwt:
          serviceAccountRef:
            name: externalsecret
        {{- end}}