## backend

replicas: 2
container:
  name: backend
  image:
    name: annleefores/backend
    version: 1.0.0
memory: "128Mi"
cpu: "500m"
imagePullPolicy: IfNotPresent

type: ClusterIP

# secret values retrieved from AWS parameter store using External Secrets Operator
eso:
  UUID_NAMESPACE: /kodiko/backend/UUID_NAMESPACE


