
controller:
  # Used for label app.kubernetes.io/component
  componentName: "jenkins-controller"
  image: "annleefores/jenkins-controller"
  tag: "latest"
  imagePullPolicy: "Always"
  numExecutors: 0

  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"

  servicePort: 8050
  targetPort: 8080
  # For minikube, set this to NodePort, elsewhere use LoadBalancer
  # Use ClusterIP if your setup includes ingress controller
  serviceType: LoadBalancer

  # List of plugins to be install during Jenkins controller start
  installPlugins: false
