{{- with .Values.main }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ quote .syncWave }}
  name: {{ $.Release.Name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: {{ $.Release.Name }}
spec:
  project: default
  source:
    repoURL: {{ .spec.source.repoURL }}
    targetRevision: {{ .spec.source.branch }}
    path: {{ .spec.source.path }}
    helm:
      {{- if $.Values.dev }}
      valueFiles:
      - dev-values.yaml
      {{- else }}
      valuesObject:
        awsLBC:
          spec:
            source:
              helm:
                valuesObject:
                    vpcId: {{ $.Values.vpcID }} 
      {{- end }}

  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.ns }}
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
{{- end }}   