apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: system-config
spec:
  project: default
  source:
    repoURL: https://github.com/annleefores/kodiko.git
    targetRevision: dev
    path: kubernetes/system-config/config-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    