{{- if .Values.eks }}
{{- with .Values.aws-lbc }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave }}
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: aws-load-balancer-controller
spec:
  project: default
  source:
    repoURL: {{ .spec.source.repoURL }}
    targetRevision: {{ .spec.source.targetRevision }}
    chart: {{ .spec.source.chart }}
    helm:
        releaseName: {{ .spec.source.helm.releaseName }}
        {{- with .spec.source.helm.valuesObject }}
        valuesObject:
            clusterName: {{ .clusterName }}
            serviceAccount:
                create: {{ .serviceAccount.create }}
                name: {{ .serviceAccount.name }}
            region: {{ .region }}
            vpcId: {{ .vpcId }}
        {{- end}}
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.ns }}
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
{{- end}}
{{- end}}