{{- with .Values.aws-lbc }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave }}
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: external-secrets-operator
spec:
  project: default
  source:
    repoURL: {{ .spec.source.repoURL }}
    targetRevision: {{ .spec.source.targetRevision }}
    chart: {{ .spec.source.chart }}
    helm:
        releaseName: external-secrets
        {{- with .spec.source.helm.valuesObject }}
        valuesObject:
            installCRDs: {{ .installCRDs }}
            webhook:
              port: {{ .webhook.port }}
        {{- end}}

  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.ns }}
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end}}  