apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-extsecret
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: argocd-image-updater-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .GITHUB_USERNAME }}"
        password: "{{ .GITHUB_TOKEN }}"

  data:
  - secretKey: GITHUB_USERNAME
    remoteRef:
      key: /kodiko/backend/local/GITHUB_USERNAME
  - secretKey: GITHUB_TOKEN # token with write access to repo
    remoteRef:
      key: /kodiko/backend/local/GITHUB_TOKEN