# prod or dev: bool
dev: false

spec:
  source:
    branch: dev
    path: kubernetes/system-config/apps
    repoURL: https://github.com/annleefores/kodiko.git

destination:
  server: https://kubernetes.default.svc
  ns: default

# EKS Cluster VPC ID - update this via --set
vpcID: 
