# https://external-secrets.io/main/provider/aws-parameter-store/


apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        {{- if .Values.eks }}
        jwt:
          serviceAccountRef:
            name: externalsecret
        {{- else }}
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
        {{- end}}