# https://external-secrets.io/main/provider/aws-parameter-store/


apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        {{- if .Values.eks }}
        jwt:
          # specify serviceaccount ns - https://github.com/external-secrets/external-secrets/issues/2065s
          serviceAccountRef:
            name: externalsecret
            namespace: external-secrets
        {{- else }}
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: external-secrets
        {{- end}}