apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: backend
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: {{ .Values.spec.source.path }}
    {{- if .Values.dev }}
    helm:
      valueFiles:
      - dev-values.yaml
    {{- end }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.ns }}
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
    - CreateNamespace=true
    