apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: annleefores/kodiko-backend:~1.0
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-secret
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: backend
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: {{ .Values.spec.source.path }}
    {{- if .Values.dev }}
    helm:
      parameters:
        - name: backend.image.name
          value: annleefores/kodiko-backend
        - name: backend.image.tag
          value: 1.0.3
      valueFiles:
      - dev-values.yaml
    {{- end }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.ns }}
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
    - CreateNamespace=true
    