mainIngress:
  host: '*.kodiko.xyz'

nginxIngress:
  host: api.kodiko.xyz
  port: 80

argocd:
  host: argocd.kodiko.xyz

kaniko:
  dockerUsername: /kodiko/backend/DOCKER_USERNAME
  dockerSecret: /kodiko/backend/DOCKER_SECRET
  dockerEmail: /kodiko/backend/DOCKER_EMAIL
  registryHost: /kodiko/backend/DOCKER_REGISTRY_HOST
  ns: jenkins

# eks or local: boolean
eks: true