# https://external-secrets.io/main/api/externalsecret/
# https://external-secrets.io/latest/api/externalsecret/

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-externalsecret
spec:
  refreshInterval: '0'
  secretStoreRef:
    name: parameterstore
    kind: SecretStore
  target:
    name: backend-secret
    template:
      engineVersion: v2
      data:
        {{- range $key, $val := .Values.eso }}
        {{ $key }}: "{{ include "eso.render" $key }}"   
        {{- end }}
  data:
  {{- range $key, $val := .Values.eso }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $val }}
  {{- end }}
