apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image.name }}:{{ .Values.container.image.version }}
          resources:
            limits:
              memory: {{ .Values.memory | quote }}
              cpu: {{ .Values.cpu | quote }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-secret
          imagePullPolicy: {{ .Values.imagePullPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: backend
  type: {{ .Values.type }} 
  ports:
    - port: 8000
      targetPort: 8000
